window.HesteVennData = {
  users: [
    { id: 'USER-001', name: 'Nora Berg', role: 'Begge', location: 'Lillehammer', experienceLevel: 'Erfaren', yearsOfExperience: 12, email: 'nora.berg@example.test', phone: '+47 400 12 301', biography: 'Rolig og strukturert hestevenn som liker tur og lett dressur.', active: true },
    { id: 'USER-002', name: 'Ida Solheim', role: 'Rytter', location: 'Lillehammer', experienceLevel: 'Øvet', yearsOfExperience: 6, email: 'ida.solheim@example.test', phone: '+47 400 12 302', biography: 'Trives best ute på tur og bidrar gjerne med stell.', active: true },
    { id: 'USER-003', name: 'Erik Lunde', role: 'Hesteeier', location: 'Kristiansand', experienceLevel: 'Erfaren', yearsOfExperience: 18, email: 'erik.lunde@example.test', phone: '+47 400 12 303', biography: 'Driver et lite, rolig stallmiljø på Kristiansand.', active: true },
    { id: 'USER-004', name: 'Maja Nilsen', role: 'Rytter', location: 'Kristiansand', experienceLevel: 'Nybegynner', yearsOfExperience: 2, email: 'maja.nilsen@example.test', phone: '+47 400 12 304', biography: 'Lærer grunnleggende ridning med stor nysgjerrighet.', active: true },
    { id: 'USER-005', name: 'Sindre Haugen', role: 'Hesteeier', location: 'Asker', experienceLevel: 'Øvet', yearsOfExperience: 9, email: 'sindre.haugen@example.test', phone: '+47 400 12 305', biography: 'Opptatt av hestevelferd, trygghet og god kommunikasjon.', active: true },
    { id: 'USER-006', name: 'Liv Rønning', role: 'Begge', location: 'Hamar', experienceLevel: 'Øvet', yearsOfExperience: 8, email: 'liv.ronning@example.test', phone: '+47 400 12 306', biography: 'Allround rytter med forkjærlighet for fjordhester.', active: false }
  ],
  horses: [
    { id: 'HORSE-001', name: 'Fjellglimt', ownerId: 'USER-001', age: 11, breed: 'Nordlandshest', gender: 'Vallak', height: '142 cm', location: 'Kristiansand', experienceRequirement: 'Øvet rytter', temperament: 'Rolig og nysgjerrig', suitableActivities: ['Turridning', 'Lett dressur'], description: 'En stødig turkamerat som liker faste rutiner og rolige stier.', imageUrl: '', active: true },
    { id: 'HORSE-002', name: 'Solstjerne', ownerId: 'USER-005', age: 8, breed: 'Fjordhest', gender: 'Hoppe', height: '148 cm', location: 'Asker', experienceRequirement: 'Erfaren rytter', temperament: 'Følsom og lærevillig', suitableActivities: ['Dressur', 'Banearbeid'], description: 'Lærevillig fjordhest som trives med tydelig og rolig trening.', imageUrl: '', active: true },
    { id: 'HORSE-003', name: 'Ember', ownerId: 'USER-003', age: 14, breed: 'Dølahest', gender: 'Vallak', height: '155 cm', location: 'Lillehammer', experienceRequirement: 'Trygg nybegynner', temperament: 'Vennlig og trygg', suitableActivities: ['Skogstur', 'Kjøring'], description: 'Livserfaren og barnevennlig hest for rolige turer.', imageUrl: '', active: true },
    { id: 'HORSE-004', name: 'Måneskinn', ownerId: 'USER-006', age: 10, breed: 'Islandshest', gender: 'Hoppe', height: '138 cm', location: 'Hamar', experienceRequirement: 'Øvet rytter', temperament: 'Energisk og sosial', suitableActivities: ['Turridning', 'Gangart'], description: 'Sosial islandshest med mye fremdrift og godt humør.', imageUrl: '', active: true },
    { id: 'HORSE-005', name: 'Komet', ownerId: 'USER-003', age: 7, breed: 'Varmblodstraver', gender: 'Vallak', height: '162 cm', location: 'Kristiansand', experienceRequirement: 'Erfaren rytter', temperament: 'Konsentrert og arbeidsvillig', suitableActivities: ['Markarbeid', 'Tur'], description: 'Arbeidsvillig unghest som bygger erfaring med variert arbeid.', imageUrl: '', active: true },
    { id: 'HORSE-006', name: 'Hassel', ownerId: 'USER-005', age: 16, breed: 'Norsk kaldblod', gender: 'Vallak', height: '158 cm', location: 'Asker', experienceRequirement: 'Alle nivåer', temperament: 'Stødig og tålmodig', suitableActivities: ['Tur', 'Kjøring'], description: 'Tålmodig veteran som liker selskap og rolige dager.', imageUrl: '', active: true }
  ],
  wishes: [
    { id: 'WISH-001', name: 'Idas rideønske', userId: 'USER-002', horseId: '', location: 'Lillehammer', experience: 'Øvet', qualifications: ['Trygg på tur'], ridingStyles: ['Tur', 'Dressur'], horseSize: '135–155 cm', comment: 'Ønsker en rolig hest til faste turer én til to ganger i uken.' },
    { id: 'WISH-002', name: 'Majas første ridevenn', userId: 'USER-004', horseId: '', location: 'Kristiansand', experience: 'Nybegynner', qualifications: ['Grunnleggende håndtering'], ridingStyles: ['Tur'], horseSize: 'Under 150 cm', comment: 'Ser etter en trygg og tålmodig lærehest.' },
    { id: 'WISH-003', name: 'Noras allroundønske', userId: 'USER-001', horseId: '', location: 'Lillehammer', experience: 'Erfaren', qualifications: ['Dressurarbeid'], ridingStyles: ['Dressur', 'Tur'], horseSize: '145–165 cm', comment: 'Kan bidra med både trening, tur og stallarbeid.' },
    { id: 'WISH-004', name: 'Rytter til Fjellglimt', userId: '', horseId: 'HORSE-001', location: 'Kristiansand', experience: 'Øvet', qualifications: ['Trygg på tur'], ridingStyles: ['Tur', 'Dressur'], horseSize: 'Ikke relevant', comment: 'Søker en rolig rytter som liker skogstur og lett dressur.' },
    { id: 'WISH-005', name: 'Rytter til Solstjerne', userId: '', horseId: 'HORSE-002', location: 'Asker', experience: 'Erfaren', qualifications: ['Dressurarbeid'], ridingStyles: ['Dressur', 'Sprang'], horseSize: 'Ikke relevant', comment: 'Tydelig og balansert rytter med erfaring fra følsomme hester.' },
    { id: 'WISH-006', name: 'Turvenn til Ember', userId: '', horseId: 'HORSE-003', location: 'Lillehammer', experience: 'Nybegynner', qualifications: ['Grunnleggende håndtering'], ridingStyles: ['Tur'], horseSize: 'Ikke relevant', comment: 'Trygg person som ønsker rolige turer og gjerne hjelper til med stell.' }
  ],
  requests: [
    { id: 'REQUEST-001', name: 'Forespørsel 2026-10-03 10:00', horseId: 'HORSE-001', userId: 'USER-002', date: '2026-10-03', startTime: '10:00', durationHours: 2, activityType: 'Tur', status: 'Under behandling', comment: 'Ønsker en rolig formiddagstur.' },
    { id: 'REQUEST-002', name: 'Forespørsel 2026-10-05 17:30', horseId: 'HORSE-002', userId: 'USER-001', date: '2026-10-05', startTime: '17:30', durationHours: 1, activityType: 'Dressur', status: 'Godkjent', comment: 'Lett dressurøkt på banen.' },
    { id: 'REQUEST-003', name: 'Forespørsel 2026-10-08 12:00', horseId: 'HORSE-003', userId: 'USER-004', date: '2026-10-08', startTime: '12:00', durationHours: 1.5, activityType: 'Fôr', status: 'Avslått', comment: 'Kan hjelpe med fôring og stell.' }
  ],
  events: [
    { id: 'EVENT-001', name: 'Fellestur ved Mesna', organizerId: 'USER-001', location: 'Lillehammer', date: '2026-10-17', startTime: '11:00', qualifications: ['Trygg på tur'], description: 'Rolig fellestur med pause underveis.', participantIds: ['USER-002'] },
    { id: 'EVENT-002', name: 'Introduksjon til dressur', organizerId: 'USER-005', location: 'Asker', date: '2026-10-20', startTime: '18:00', qualifications: ['Grunnleggende rideerfaring'], description: 'En sosial kveld med enkle dressurøvelser.', participantIds: ['USER-001'] },
    { id: 'EVENT-003', name: 'Stelldag i stallen', organizerId: 'USER-003', location: 'Kristiansand', date: '2026-10-24', startTime: '10:00', qualifications: ['Ingen forkunnskaper'], description: 'Felles stell, puss og rydding i stallen.', participantIds: ['USER-004', 'USER-006'] },
    { id: 'EVENT-004', name: 'Leirskole i høstferien', organizerId: 'USER-006', location: 'Kristiansand', date: '2026-10-31', startTime: '12:30', qualifications: ['For alle'], description: 'Bli med på leirskole i stallen i høstferien', participantIds: [] }
  ],
  activities: [
    { id: 'ACTIVITY-001', name: 'Skogstur i rolig tempo', horseId: 'HORSE-001', userId: 'USER-002', activityType: 'Turridning', date: '2026-09-20', startTime: '10:30', duration: '90 min', location: 'Kristiansand', status: 'Godkjent', notes: 'Møtes ved ridebanen.' },
    { id: 'ACTIVITY-002', name: 'Lett dressurøkt', horseId: 'HORSE-001', userId: 'USER-001', activityType: 'Dressur', date: '2026-09-22', startTime: '17:00', duration: '60 min', location: 'Kristiansand', status: 'Planlagt', notes: 'Fokus på overganger.' },
    { id: 'ACTIVITY-003', name: 'Trygg førstetur', horseId: 'HORSE-003', userId: 'USER-004', activityType: 'Turridning', date: '2026-09-21', startTime: '11:00', duration: '60 min', location: 'Lillehammer', status: 'Gjennomført', notes: 'Kort runde ved Mesna.' },
    { id: 'ACTIVITY-004', name: 'Stell og miljøtrening', horseId: 'HORSE-003', userId: 'USER-002', activityType: 'Stell', date: '2026-09-23', startTime: '16:30', duration: '45 min', location: 'Lillehammer', status: 'Godkjent', notes: '' },
    { id: 'ACTIVITY-005', name: 'Banearbeid', horseId: 'HORSE-002', userId: 'USER-001', activityType: 'Dressur', date: '2026-09-24', startTime: '18:00', duration: '60 min', location: 'Asker', status: 'Planlagt', notes: 'Ta med egne hansker.' },
    { id: 'ACTIVITY-006', name: 'Gangartstur', horseId: 'HORSE-004', userId: 'USER-006', activityType: 'Turridning', date: '2026-09-25', startTime: '12:00', duration: '120 min', location: 'Hamar', status: 'Planlagt', notes: '' },
    { id: 'ACTIVITY-007', name: 'Grunnarbeid', horseId: 'HORSE-005', userId: 'USER-003', activityType: 'Markarbeid', date: '2026-09-26', startTime: '09:00', duration: '45 min', location: 'Kristiansand', status: 'Avlyst', notes: 'Flyttes til neste uke.' },
    { id: 'ACTIVITY-008', name: 'Rolig kveldstur', horseId: 'HORSE-006', userId: 'USER-004', activityType: 'Tur', date: '2026-09-27', startTime: '18:30', duration: '75 min', location: 'Asker', status: 'Godkjent', notes: '' },
    { id: 'ACTIVITY-009', name: 'Kjøring på tunet', horseId: 'HORSE-003', userId: 'USER-006', activityType: 'Kjøring', date: '2026-09-28', startTime: '10:00', duration: '60 min', location: 'Lillehammer', status: 'Planlagt', notes: '' },
    { id: 'ACTIVITY-010', name: 'Dressur med instruktør', horseId: 'HORSE-002', userId: 'USER-005', activityType: 'Dressur', date: '2026-09-29', startTime: '17:30', duration: '60 min', location: 'Asker', status: 'Gjennomført', notes: 'God fremgang i skritt.' }
  ],
  qualifications: [
    { id: 'QUALIFICATION-001', name: 'Trygg på tur', userId: 'USER-002', horseId: 'HORSE-001', qualificationType: 'Turridning', level: 'Øvet', status: 'Godkjent', description: 'Kan ri alene på kjente stier.', validFrom: '2026-01-15', validUntil: '2027-01-15' },
    { id: 'QUALIFICATION-002', name: 'Stell og håndtering', userId: 'USER-004', horseId: 'HORSE-003', qualificationType: 'Hestehold', level: 'Grunnleggende', status: 'Foreslått', description: 'Introduksjon til daglig stell.', validFrom: '2026-09-01', validUntil: '2027-09-01' },
    { id: 'QUALIFICATION-003', name: 'Dressurarbeid', userId: 'USER-001', horseId: 'HORSE-002', qualificationType: 'Dressur', level: 'Erfaren', status: 'Godkjent', description: 'Lang erfaring med grunnleggende dressur.', validFrom: '2026-02-01', validUntil: '2027-02-01' },
    { id: 'QUALIFICATION-004', name: 'Ansvarlig rytter', userId: 'USER-006', horseId: 'HORSE-004', qualificationType: 'Turridning', level: 'Øvet', status: 'Utløpt', description: 'Tidligere godkjenning for lengre turer.', validFrom: '2025-01-01', validUntil: '2026-01-01' },
    { id: 'QUALIFICATION-005', name: 'Grunnleggende håndtering', userId: 'USER-004', horseId: 'HORSE-006', qualificationType: 'Hestehold', level: 'Grunnleggende', status: 'Godkjent', description: 'Trygg i stall og ved leietrening.', validFrom: '2026-05-01', validUntil: '2027-05-01' },
    { id: 'QUALIFICATION-006', name: 'Kjøring', userId: 'USER-003', horseId: 'HORSE-003', qualificationType: 'Kjøring', level: 'Erfaren', status: 'Godkjent', description: 'Godkjent for rolig kjøring med Ember.', validFrom: '2026-03-10', validUntil: '2027-03-10' },
    { id: 'QUALIFICATION-007', name: 'Unghestarbeid', userId: 'USER-001', horseId: 'HORSE-005', qualificationType: 'Markarbeid', level: 'Erfaren', status: 'Godkjent', description: 'Erfaring med trygg grunntrening.', validFrom: '2026-04-01', validUntil: '2027-04-01' },
    { id: 'QUALIFICATION-008', name: 'Turvenn', userId: 'USER-002', horseId: 'HORSE-006', qualificationType: 'Tur', level: 'Øvet', status: 'Foreslått', description: 'Passer til rolige turer i nærområdet.', validFrom: '2026-09-01', validUntil: '2027-09-01' }
  ],
  incidents: [
    { id: 'INCIDENT-001', name: 'Liten skramme på venstre kode', horseId: 'HORSE-001', date: '2026-08-12', incidentType: 'Skade', severity: 'Lav', description: 'Overflatisk skramme etter beiting.', actionTaken: 'Renset og fulgt opp daglig.', status: 'Lukket' },
    { id: 'INCIDENT-002', name: 'Uro ved lasting', horseId: 'HORSE-002', date: '2026-07-18', incidentType: 'Atferd', severity: 'Middels', description: 'Solstjerne ble urolig ved lasting.', actionTaken: 'Treningsplan med korte økter.', status: 'Under oppfølging' },
    { id: 'INCIDENT-003', name: 'Snubling på tur', horseId: 'HORSE-003', date: '2026-06-09', incidentType: 'Hendelse', severity: 'Lav', description: 'Snublet uten synlig skade.', actionTaken: 'Pause og sjekk av hovstell.', status: 'Lukket' },
    { id: 'INCIDENT-004', name: 'Stivhet etter trening', horseId: 'HORSE-004', date: '2026-09-02', incidentType: 'Helse', severity: 'Middels', description: 'Noe stiv i bakparten dagen etter økt.', actionTaken: 'Hvile og avtalt oppfølging.', status: 'Åpen' },
    { id: 'INCIDENT-005', name: 'Løs sko', horseId: 'HORSE-005', date: '2026-08-30', incidentType: 'Hov', severity: 'Lav', description: 'Høyre forsko løsnet.', actionTaken: 'Smed bestilt.', status: 'Lukket' },
    { id: 'INCIDENT-006', name: 'Fall i paddock', horseId: 'HORSE-002', date: '2026-05-22', incidentType: 'Hendelse', severity: 'Høy', description: 'Fall uten rytter i våt paddock.', actionTaken: 'Veterinær undersøkte, rolig opptrapping.', status: 'Lukket' }
  ]
};
