window.HesteVennData = {
  users: [
    { id: 'USER-001', name: 'Nora Berg', role: 'Begge', location: 'Agder', experienceLevel: 'Erfaren', yearsOfExperience: 12, email: 'nora.berg@example.test', phone: '+47 400 12 301', biography: 'Trygg og strukturert rytter med fokus på hestevelferd.', active: true },
    { id: 'USER-002', name: 'Ida Solheim', role: 'Begge', location: 'Agder', experienceLevel: 'Øvet', yearsOfExperience: 7, email: 'ida.solheim@example.test', phone: '+47 400 12 302', biography: 'Liker rolige turer og faste rutiner i stallen.', active: true },
    { id: 'USER-003', name: 'Erik Lunde', role: 'Begge', location: 'Agder', experienceLevel: 'Erfaren', yearsOfExperience: 18, email: 'erik.lunde@example.test', phone: '+47 400 12 303', biography: 'Stallansvarlig med erfaring fra unghest og tur.', active: true },
    { id: 'USER-004', name: 'Maja Nilsen', role: 'Rytter', location: 'Agder', experienceLevel: 'Nybegynner', yearsOfExperience: 2, email: 'maja.nilsen@example.test', phone: '+47 400 12 304', biography: 'Motivert nybegynner som vil ri jevnlig.', active: true },
    { id: 'USER-005', name: 'Sindre Haugen', role: 'Hesteeier', location: 'Agder', experienceLevel: 'Øvet', yearsOfExperience: 9, email: 'sindre.haugen@example.test', phone: '+47 400 12 305', biography: 'Opptatt av trygg matching mellom hest og rytter.', active: true },
    { id: 'USER-006', name: 'Liv Rønning', role: 'Begge', location: 'Agder', experienceLevel: 'Øvet', yearsOfExperience: 8, email: 'liv.ronning@example.test', phone: '+47 400 12 306', biography: 'Allround rytter med sans for variasjon.', active: true },
    { id: 'USER-007', name: 'Kari Aas', role: 'Rytter', location: 'Agder', experienceLevel: 'Øvet', yearsOfExperience: 4, email: 'kari.aas@example.test', phone: '+47 400 12 307', biography: 'Liker dressur og korte turøkter.', active: true },
    { id: 'USER-008', name: 'Ole Martinsen', role: 'Hesteeier', location: 'Agder', experienceLevel: 'Erfaren', yearsOfExperience: 11, email: 'ole.martinsen@example.test', phone: '+47 400 12 308', biography: 'Har fokus på stabil trening og godt samarbeid.', active: true },
    { id: 'USER-009', name: 'Anne Viken', role: 'Rytter', location: 'Agder', experienceLevel: 'Nybegynner', yearsOfExperience: 1, email: 'anne.viken@example.test', phone: '+47 400 12 309', biography: 'Vil lære mer om hestehold i trygge rammer.', active: true },
    { id: 'USER-010', name: 'Jonas Dahl', role: 'Begge', location: 'Agder', experienceLevel: 'Erfaren', yearsOfExperience: 14, email: 'jonas.dahl@example.test', phone: '+47 400 12 310', biography: 'Erfaren tur- og dressurrytter med rolig stil.', active: true }
  ],
  horses: [
    { id: 'HORSE-001', name: 'Fjellglimt', ownerId: 'USER-001', age: 11, breed: 'Nordlandshest', gender: 'Vallak', height: '142 cm', location: 'Agder', experienceRequirement: 'Øvet rytter', temperament: 'Rolig og nysgjerrig', suitableActivities: ['Turridning', 'Lett dressur'], description: 'Stødig turkamerat med jevnt temperament.', imageUrl: '', active: true },
    { id: 'HORSE-002', name: 'Bris', ownerId: 'USER-001', age: 9, breed: 'Fjordhest', gender: 'Hoppe', height: '146 cm', location: 'Agder', experienceRequirement: 'Alle nivåer', temperament: 'Snill og stabil', suitableActivities: ['Tur', 'Stell'], description: 'Trygg hest for jevne turer.', imageUrl: '', active: true },
    { id: 'HORSE-003', name: 'Mørk', ownerId: 'USER-001', age: 7, breed: 'Islandshest', gender: 'Vallak', height: '138 cm', location: 'Agder', experienceRequirement: 'Trygg nybegynner', temperament: 'Våken og sosial', suitableActivities: ['Turridning', 'Gangart'], description: 'Sosial hest med god fremdrift.', imageUrl: '', active: true },
    { id: 'HORSE-004', name: 'Solstjerne', ownerId: 'USER-002', age: 8, breed: 'Fjordhest', gender: 'Hoppe', height: '148 cm', location: 'Agder', experienceRequirement: 'Erfaren rytter', temperament: 'Følsom og lærevillig', suitableActivities: ['Dressur', 'Markarbeid'], description: 'Lærevillig hest for strukturert ridning.', imageUrl: '', active: true },
    { id: 'HORSE-005', name: 'Kastanje', ownerId: 'USER-002', age: 13, breed: 'Dølahest', gender: 'Vallak', height: '154 cm', location: 'Agder', experienceRequirement: 'Alle nivåer', temperament: 'Trygg og rolig', suitableActivities: ['Tur', 'Kjøring'], description: 'Trygg veteran med stor arbeidslyst.', imageUrl: '', active: true },
    { id: 'HORSE-006', name: 'Luna', ownerId: 'USER-002', age: 6, breed: 'Norsk varmblod', gender: 'Hoppe', height: '160 cm', location: 'Agder', experienceRequirement: 'Øvet rytter', temperament: 'Energisk', suitableActivities: ['Dressur', 'Sprang'], description: 'Ung hest som bygger erfaring.', imageUrl: '', active: true },
    { id: 'HORSE-007', name: 'Ember', ownerId: 'USER-003', age: 14, breed: 'Dølahest', gender: 'Vallak', height: '155 cm', location: 'Agder', experienceRequirement: 'Trygg nybegynner', temperament: 'Vennlig og trygg', suitableActivities: ['Skogstur', 'Stell'], description: 'Barnevennlig og rolig hest.', imageUrl: '', active: true },
    { id: 'HORSE-008', name: 'Komet', ownerId: 'USER-003', age: 7, breed: 'Varmblodstraver', gender: 'Vallak', height: '162 cm', location: 'Agder', experienceRequirement: 'Erfaren rytter', temperament: 'Konsentrert', suitableActivities: ['Markarbeid', 'Tur'], description: 'Arbeidsvillig hest som liker tydelig rytme.', imageUrl: '', active: true },
    { id: 'HORSE-009', name: 'Hassel', ownerId: 'USER-003', age: 16, breed: 'Norsk kaldblod', gender: 'Vallak', height: '158 cm', location: 'Agder', experienceRequirement: 'Alle nivåer', temperament: 'Stødig og tålmodig', suitableActivities: ['Tur', 'Kjøring'], description: 'Tålmodig veteran for rolig aktivitet.', imageUrl: '', active: true },
    { id: 'HORSE-010', name: 'Måneskinn', ownerId: 'USER-004', age: 10, breed: 'Islandshest', gender: 'Hoppe', height: '139 cm', location: 'Agder', experienceRequirement: 'Øvet rytter', temperament: 'Fremover og blid', suitableActivities: ['Turridning', 'Gangart'], description: 'Sosial hest med godt driv.', imageUrl: '', active: true },
    { id: 'HORSE-011', name: 'Ravn', ownerId: 'USER-005', age: 12, breed: 'Frieser', gender: 'Vallak', height: '165 cm', location: 'Agder', experienceRequirement: 'Erfaren rytter', temperament: 'Sterk og lydhør', suitableActivities: ['Dressur', 'Tur'], description: 'Kraftfull hest med stabilt hode.', imageUrl: '', active: true },
    { id: 'HORSE-012', name: 'Fonn', ownerId: 'USER-006', age: 9, breed: 'Fjordhest', gender: 'Vallak', height: '147 cm', location: 'Agder', experienceRequirement: 'Alle nivåer', temperament: 'Rolig og enkel', suitableActivities: ['Tur', 'Stell'], description: 'Trygg hest for hverdagsridning.', imageUrl: '', active: true },
    { id: 'HORSE-013', name: 'Stella', ownerId: 'USER-007', age: 8, breed: 'Connemara', gender: 'Hoppe', height: '150 cm', location: 'Agder', experienceRequirement: 'Øvet rytter', temperament: 'Positiv og kvikk', suitableActivities: ['Dressur', 'Tur'], description: 'Samarbeidsvillig ponni med god balanse.', imageUrl: '', active: true },
    { id: 'HORSE-014', name: 'Atlas', ownerId: 'USER-008', age: 15, breed: 'Norsk varmblod', gender: 'Vallak', height: '168 cm', location: 'Agder', experienceRequirement: 'Erfaren rytter', temperament: 'Stor, men rolig', suitableActivities: ['Tur', 'Banearbeid'], description: 'Ryddig ridehest med god kapasitet.', imageUrl: '', active: true },
    { id: 'HORSE-015', name: 'Milo', ownerId: 'USER-009', age: 6, breed: 'Welsh cob', gender: 'Vallak', height: '145 cm', location: 'Agder', experienceRequirement: 'Trygg nybegynner', temperament: 'Vennlig og myk', suitableActivities: ['Tur', 'Grunnarbeid'], description: 'Ung og snill hest for gradvis progresjon.', imageUrl: '', active: true },
    { id: 'HORSE-016', name: 'Saga', ownerId: 'USER-010', age: 11, breed: 'Oldenburger', gender: 'Hoppe', height: '166 cm', location: 'Agder', experienceRequirement: 'Øvet rytter', temperament: 'Arbeidsvillig', suitableActivities: ['Dressur', 'Tur'], description: 'Balansert hest med god ridbarhet.', imageUrl: '', active: true }
  ],
  wishes: [
    { id: 'WISH-001', name: 'Nora ønsker å ri dressur', userId: 'USER-001', horseId: '', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Erfaren', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Ukentlig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Ønsker 1-2 faste økter i uka.' },
    { id: 'WISH-002', name: 'Fjellglimt ønsker lett øvet rytter', userId: '', horseId: 'HORSE-001', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Lett øvet', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Ukentlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Rolig rytter med gode rutiner.' },
    { id: 'WISH-003', name: 'Ida ønsker å ri tur', userId: 'USER-002', horseId: '', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Lett øvet', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Månedlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Grunnleggende håndtering'], comment: 'Helst helg formiddag.' },
    { id: 'WISH-004', name: 'Solstjerne ønsker erfaren rytter', userId: '', horseId: 'HORSE-004', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Erfaren', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Ukentlig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Dressurarbeid'], comment: 'Ønsker en tydelig rytter.' },
    { id: 'WISH-005', name: 'Erik ønsker å ri tur', userId: 'USER-003', horseId: '', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Erfaren', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Engangstilfelle', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Kan på kort varsel.' },
    { id: 'WISH-006', name: 'Ember ønsker nybegynner rytter', userId: '', horseId: 'HORSE-007', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Nybegynner', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Ukentlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Grunnleggende håndtering'], comment: 'Trygg lærehest for ny rytter.' },
    { id: 'WISH-007', name: 'Maja ønsker å ri tur', userId: 'USER-004', horseId: '', location: 'Agder', størrelsePåHest: 'Liten', erfaring: 'Nybegynner', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Ukentlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Ingen forkunnskaper'], comment: 'Vil ha trygg oppstart.' },
    { id: 'WISH-008', name: 'Måneskinn ønsker lett øvet rytter', userId: '', horseId: 'HORSE-010', location: 'Agder', størrelsePåHest: 'Liten', erfaring: 'Lett øvet', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Månedlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Sosial rytter ønskes.' },
    { id: 'WISH-009', name: 'Sindre ønsker å ri dressur', userId: 'USER-005', horseId: '', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Øvet', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Ukentlig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Dressurarbeid'], comment: 'Fokus på teknikk og rytme.' },
    { id: 'WISH-010', name: 'Ravn ønsker erfaren rytter', userId: '', horseId: 'HORSE-011', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Erfaren', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Daglig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Ansvarlig rytter'], comment: 'Kun erfaren rytter.' },
    { id: 'WISH-011', name: 'Liv ønsker å ri tur', userId: 'USER-006', horseId: '', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Øvet', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Ukentlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Allround aktivitet passer best.' },
    { id: 'WISH-012', name: 'Fonn ønsker nybegynner rytter', userId: '', horseId: 'HORSE-012', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Nybegynner', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Periode', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Grunnleggende håndtering'], comment: 'Trygg og stabil match ønskes.' },
    { id: 'WISH-013', name: 'Kari ønsker å ri dressur', userId: 'USER-007', horseId: '', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Lett øvet', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Månedlig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Dressurarbeid'], comment: 'Ønsker økter med tydelige mål.' },
    { id: 'WISH-014', name: 'Stella ønsker lett øvet rytter', userId: '', horseId: 'HORSE-013', location: 'Agder', størrelsePåHest: 'Mellom', erfaring: 'Lett øvet', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Ukentlig', ridestil: 'Sprang', status: 'Aktiv', qualifications: ['Grunnleggende håndtering'], comment: 'Spranginteresse er en fordel.' },
    { id: 'WISH-015', name: 'Ole ønsker å ri tur', userId: 'USER-008', horseId: '', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Erfaren', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Engangstilfelle', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Gjerne langtur i helg.' },
    { id: 'WISH-016', name: 'Atlas ønsker erfaren rytter', userId: '', horseId: 'HORSE-014', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Erfaren', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Ukentlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Ansvarlig rytter'], comment: 'Trygg rytter med rolig hånd.' },
    { id: 'WISH-017', name: 'Anne ønsker å ri tur', userId: 'USER-009', horseId: '', location: 'Agder', størrelsePåHest: 'Liten', erfaring: 'Nybegynner', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Ukentlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Ingen forkunnskaper'], comment: 'Ønsker korte økter med veiledning.' },
    { id: 'WISH-018', name: 'Milo ønsker nybegynner rytter', userId: '', horseId: 'HORSE-015', location: 'Agder', størrelsePåHest: 'Liten', erfaring: 'Nybegynner', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Månedlig', ridestil: 'Tur', status: 'Aktiv', qualifications: ['Grunnleggende håndtering'], comment: 'Passer godt for nybegynner.' },
    { id: 'WISH-019', name: 'Jonas ønsker å ri dressur', userId: 'USER-010', horseId: '', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Erfaren', ønsketype: 'Ønsker å Ri', aktivitetstype: 'Ukentlig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Dressurarbeid'], comment: 'Gjerne kombinasjon av bane og tur.' },
    { id: 'WISH-020', name: 'Saga ønsker øvet rytter', userId: '', horseId: 'HORSE-016', location: 'Agder', størrelsePåHest: 'Stor', erfaring: 'Øvet', ønsketype: 'Ønsker en rytter', aktivitetstype: 'Ukentlig', ridestil: 'Dressur', status: 'Aktiv', qualifications: ['Trygg på tur'], comment: 'Ønsker stabil rytterprofil.' }
  ],
  requests: [
    { id: 'REQUEST-001', name: 'FS-0001', wishId: 'WISH-002', sender: 'USER-004', mottaker: 'USER-001', horseId: 'HORSE-001', userId: 'USER-004', date: '2026-10-03', startTime: '10:00', durationHours: 2, activityType: 'Tur', status: 'Under behandling', comment: 'Ønsker en rolig formiddagstur.' },
    { id: 'REQUEST-002', name: 'FS-0002', wishId: 'WISH-004', sender: 'USER-007', mottaker: 'USER-002', horseId: 'HORSE-004', userId: 'USER-007', date: '2026-10-04', startTime: '17:30', durationHours: 1, activityType: 'Dressur', status: 'Godkjent', comment: 'Lett dressurøkt på bane.' },
    { id: 'REQUEST-003', name: 'FS-0003', wishId: 'WISH-006', sender: 'USER-009', mottaker: 'USER-003', horseId: 'HORSE-007', userId: 'USER-009', date: '2026-10-05', startTime: '12:00', durationHours: 1.5, activityType: 'Tur', status: 'Avslått', comment: 'Kan hjelpe med stell i tillegg.' },
    { id: 'REQUEST-004', name: 'FS-0004', wishId: 'WISH-010', sender: 'USER-010', mottaker: 'USER-005', horseId: 'HORSE-011', userId: 'USER-010', date: '2026-10-06', startTime: '18:00', durationHours: 1, activityType: 'Dressur', status: 'Under behandling', comment: 'Ønsker kveldstrening.' }
  ],
  events: [
    { id: 'EVENT-001', name: 'Fellestur i Agder nord', organizerId: 'USER-001', location: 'Agder', date: '2026-10-17', startTime: '11:00', qualifications: ['Trygg på tur'], description: 'Rolig fellestur med pause underveis.', participantIds: ['USER-002', 'USER-004'] },
    { id: 'EVENT-002', name: 'Introduksjon til dressur', organizerId: 'USER-005', location: 'Agder', date: '2026-10-20', startTime: '18:00', qualifications: ['Grunnleggende rideerfaring'], description: 'Sosial kveld med enkle øvelser.', participantIds: ['USER-001', 'USER-007'] },
    { id: 'EVENT-003', name: 'Stelldag i stallen', organizerId: 'USER-003', location: 'Agder', date: '2026-10-24', startTime: '10:00', qualifications: ['Ingen forkunnskaper'], description: 'Felles stell, puss og rydding i stallen.', participantIds: ['USER-006', 'USER-009'] },
    { id: 'EVENT-004', name: 'Sprang grunnteknikk', organizerId: 'USER-002', location: 'Agder', date: '2026-10-27', startTime: '16:30', qualifications: ['Lett øvet'], description: 'Trening på rytme og linjevalg.', participantIds: ['USER-007', 'USER-010'] },
    { id: 'EVENT-005', name: 'Helgetur ved kysten', organizerId: 'USER-008', location: 'Agder', date: '2026-11-01', startTime: '09:30', qualifications: ['Trygg på tur'], description: 'Langtur i rolig tempo med felles lunsj.', participantIds: ['USER-003', 'USER-005'] }
  ],
  activities: [
    { id: 'ACTIVITY-001', name: 'Skogstur i rolig tempo', horseId: 'HORSE-001', userId: 'USER-004', activityType: 'Turridning', date: '2026-09-20', startTime: '10:30', duration: '90 min', location: 'Agder', status: 'Godkjent', notes: 'Møtes ved ridebanen.' },
    { id: 'ACTIVITY-002', name: 'Lett dressurøkt', horseId: 'HORSE-004', userId: 'USER-007', activityType: 'Dressur', date: '2026-09-22', startTime: '17:00', duration: '60 min', location: 'Agder', status: 'Planlagt', notes: 'Fokus på overganger.' },
    { id: 'ACTIVITY-003', name: 'Trygg førstetur', horseId: 'HORSE-007', userId: 'USER-009', activityType: 'Turridning', date: '2026-09-21', startTime: '11:00', duration: '60 min', location: 'Agder', status: 'Gjennomført', notes: 'Kort runde med ledsager.' },
    { id: 'ACTIVITY-004', name: 'Stell og miljøtrening', horseId: 'HORSE-012', userId: 'USER-006', activityType: 'Stell', date: '2026-09-23', startTime: '16:30', duration: '45 min', location: 'Agder', status: 'Godkjent', notes: '' },
    { id: 'ACTIVITY-005', name: 'Banearbeid', horseId: 'HORSE-016', userId: 'USER-010', activityType: 'Dressur', date: '2026-09-24', startTime: '18:00', duration: '60 min', location: 'Agder', status: 'Planlagt', notes: 'Ta med egne hansker.' },
    { id: 'ACTIVITY-006', name: 'Rolig kveldstur', horseId: 'HORSE-015', userId: 'USER-009', activityType: 'Tur', date: '2026-09-27', startTime: '18:30', duration: '75 min', location: 'Agder', status: 'Godkjent', notes: '' }
  ],
  qualifications: [
    { id: 'QUALIFICATION-001', name: 'Trygg på tur', userId: 'USER-004', horseId: 'HORSE-001', qualificationType: 'Turridning', level: 'Øvet', status: 'Godkjent', description: 'Kan ri på kjente stier.', validFrom: '2026-01-15', validUntil: '2027-01-15' },
    { id: 'QUALIFICATION-002', name: 'Grunnleggende håndtering', userId: 'USER-009', horseId: 'HORSE-007', qualificationType: 'Hestehold', level: 'Grunnleggende', status: 'Foreslått', description: 'Introduksjon til daglig stell.', validFrom: '2026-09-01', validUntil: '2027-09-01' },
    { id: 'QUALIFICATION-003', name: 'Dressurarbeid', userId: 'USER-010', horseId: 'HORSE-016', qualificationType: 'Dressur', level: 'Erfaren', status: 'Godkjent', description: 'Lang erfaring med grunnleggende dressur.', validFrom: '2026-02-01', validUntil: '2027-02-01' }
  ],
  incidents: [
    { id: 'INCIDENT-001', name: 'Liten skramme på venstre kode', horseId: 'HORSE-001', date: '2026-08-12', incidentType: 'Skade', severity: 'Lav', description: 'Overflatisk skramme etter beiting.', actionTaken: 'Renset og fulgt opp daglig.', status: 'Lukket' },
    { id: 'INCIDENT-002', name: 'Uro ved lasting', horseId: 'HORSE-004', date: '2026-07-18', incidentType: 'Atferd', severity: 'Middels', description: 'Solstjerne ble urolig ved lasting.', actionTaken: 'Treningsplan med korte økter.', status: 'Under oppfølging' },
    { id: 'INCIDENT-003', name: 'Stivhet etter trening', horseId: 'HORSE-016', date: '2026-09-02', incidentType: 'Helse', severity: 'Middels', description: 'Noe stiv i bakparten dagen etter økt.', actionTaken: 'Hvile og avtalt oppfølging.', status: 'Åpen' }
  ]
};
